# This is a basic workflow to help you get started with Actions
name: Deploy Azure DevCenters
run-name: Deploy Azure DevCenters

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "AddWorkflow" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_configuration_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.configuration-matrix.outputs.matrix }}
    steps:

      - uses: actions/checkout@v2

      - name: set-configuration_matrix
        id: configuration-matrix
        working-directory: ./devCenter/config
        run: echo "matrix=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build_devcenters:
    # Matrix of subscriptions
    strategy:
      matrix:
        configurations: ${{ fromJson(needs.build_configuration_matrix.outputs.matrix) }}

        # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build_configuration_matrix

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Get subscription from configuration file
      - name: 'Get Subscription Id'
        id: SubscriptionId
        working-directory: ./devCenter/config
        run: echo "SUBSCRIPTIONID=$(jq --raw-output .subscription ${{ matrix.configurations }})" >> $GITHUB_OUTPUT

      # Get name from configuration file
      - name: 'Get DevCenter Name'
        id: DevCenterName
        working-directory: ./devCenter/config
        run: echo "DEVCENTERNAME=$(jq --raw-output .name ${{ matrix.configurations }})" >> $GITHUB_OUTPUT
    
      # Connect to cli using openid auth
      #- name: 'Az CLI login'
      #  uses: azure/login@v1
      #  with:
      #      client-id: "${{ CLIENT_ID }}"
      #      tenant-id: ${{ TENANT_ID }}
      #      subscription-id: ${{ steps.SubscriptionId.outputs.SUBSCRIPTIONID }}

      # Create DevCenters
      - name: 'Create DevCenters ${{ steps.DevCenterName.outputs.DEVCENTERNAME }} '
        working-directory: ./devCenter
        run: echo "-s ${{ steps.SubscriptionId.outputs.SUBSCRIPTIONID }} -c './devCenter/config/${{ matrix.configurations }}'"
        #run: bash setup.sh -s ${{ steps.SubscriptionId.outputs.SUBSCRIPTIONID }} -c './devCenter/config/${{ matrix.configurations }}''
